{
 "title": "Uptimer",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "hosts", "label": "hosts", "query": { "query": "label_values(uptime_up,host)" } }
  ]
 },
 "panels": [
  {
   "title": "Latency per service",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (host) (uptime_latency{host=~\"$hosts\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(uptime_latency{host=~\"$hosts\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of offline services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(uptime_up{host=~\"$hosts\"} == 0) OR 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of available services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(uptime_up{host=~\"$hosts\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online hosts",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "uptime_up{host=~\"$hosts\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline hosts",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "uptime_up{host=~\"$hosts\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "uptime_up{host=~\"$hosts\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "uptime_latency{host=~\"$hosts\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}